### ISSUE TITLE
receive_adapter startup failed

### ISSUE THREAD

**Issue by youyongsong** [knative-extensions/eventing-gitlab#479]
**Describe the bug**
When ksrv attempt to start the eventing-gitLab receive_adapter pod, it run into the following error message, which prevents the service from starting successfully:

```
Unable to fetch k8s.io/client-go/kubernetes.Interface from context. This context is not the application context (which is typically given to constructors via sharedmain).
```

I've followed the official documentation for installation and configuration, and my Kubernetes cluster is operational. I've tried searching for similar issues but haven't found a solution yet.

 **Expected behavior**
the eventing-gitLab receive_adapter pod should start up successfully.

 **To Reproduce**
* deploy knative eventing and knative serving in kubernetes cluster
* deploy eventing-gitlab
* create a gitlabsource instance like this:

```yaml
apiVersion: sources.knative.dev/v1alpha1
kind: GitLabSource
metadata:
  name: gitlabsource-pr-comment
  namespace: default
spec:
  eventTypes:
    - "note_events"
  accessToken:
    secretKeyRef:
      name: gitlab-integration-config
      key: token
  secretToken:
    secretKeyRef:
      name: gitlab-secret-token
      key: secret_token
  projectUrl: "https://gitlab-ce.alauda.cn/idp/demo/chatops"
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
```

 **Knative release version**

v1.13.1
